# Site Settings
title: Jekyll CMS
email: jacobmiske@gmail.com
description: >
  CMS started with Jekyll.
baseurl: ""
url: "http://localhost:4000"
twitter_username: SirMiske
github_username:  Jacob Miske
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
