# Site Settings
title: A Pile of Notes - Content Management Site
email: jacobmiske@gmail.com
description: >
  Getting CMS started with Jekyll.
baseurl: "/"
url: "http://jacobmiske.github.io"
twitter_username: SirMiske
github_username:  JacobMiske
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
kramdown:
  input: GFM
mathjax: true
# Collections
collections:
  portfolio:
    output: true
